
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author atura
 */
public class Transaction extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet ra = null;
    Statement st = null;
    int sendingID;
    /**
     * Creates new form Transcaktion
     */
    public Transaction() {
        initComponents();
    }
    public Transaction(ResultSet ra) throws SQLException {
        initComponents();
        this.ra = ra;
        conn = BankDBConnection.connectBankDB();
        BalanceText.setText(ra.getString("Balance"));
        sendingID = ra.getInt("ID");
        BalanceText.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IbanLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        SurnameLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SendButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BalanceText = new javax.swing.JTextField();
        AmountEx = new javax.swing.JLabel();
        SurnameEx = new javax.swing.JLabel();
        NameEx = new javax.swing.JLabel();
        IBANEx = new javax.swing.JLabel();
        IbanText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();
        SurnameText = new javax.swing.JTextField();
        AmountText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IbanLabel.setText("IBAN:");

        NameLabel.setText("First Name:");

        SurnameLabel.setText("Last Name:");

        jLabel4.setText("Amount:");

        SendButton.setText("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Balance:");

        BalanceText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        AmountEx.setForeground(new java.awt.Color(255, 51, 0));
        AmountEx.setText(" ");

        SurnameEx.setForeground(new java.awt.Color(255, 51, 0));
        SurnameEx.setText(" ");

        NameEx.setForeground(new java.awt.Color(255, 51, 0));
        NameEx.setText(" ");

        IBANEx.setForeground(new java.awt.Color(255, 51, 51));
        IBANEx.setText(" ");

        IbanText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IbanTextKeyPressed(evt);
            }
        });

        NameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameTextKeyPressed(evt);
            }
        });

        SurnameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SurnameTextKeyPressed(evt);
            }
        });

        AmountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AmountTextKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SurnameEx)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AmountEx)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NameEx)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(IBANEx)
                        .addGap(204, 204, 204))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IbanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameLabel)
                            .addComponent(NameLabel)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BalanceText, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(IbanText)
                            .addComponent(NameText)
                            .addComponent(SurnameText)
                            .addComponent(AmountText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BalanceText))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IbanLabel)
                    .addComponent(IbanText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IBANEx)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameEx)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SurnameLabel)
                    .addComponent(SurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SurnameEx)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AmountEx)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        
     try{
            if (ra != null) 
                ra.close();
            if((Integer.parseInt(BalanceText.getText())) < (Integer.parseInt(AmountText.getText())))
            {
                System.out.print("Insufficient balance\n");
                JOptionPane.showMessageDialog(null, "Insufficient balance");
                return;
            }
            if (check() == 0)
            {
                System.out.print("The entered information does not match\n");
                JOptionPane.showMessageDialog(null, "The entered information does not match");
                return;
            }
            String transql = "insert into transactions values (?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(transql);
            Random a = new Random();
            pst.setInt(1, (a.nextInt(100)));
            pst.setString(2, (Integer.toString(sendingID)));
            Date currentDate = new Date();
            pst.setTimestamp(1, new java.sql.Timestamp(currentDate.getTime()));
            pst.setString(4, AmountText.getText());
            pst.setString(5, IbanText.getText());
            pst.execute();
            pst.close();
            st = conn.createStatement();
            ra = st.executeQuery("SELECT * FROM accounts WHERE ID=" + (Integer.toString(sendingID)));
            pst.close();
            Sendingaccount();
            Receivingaccount();
            homepage();
            System.out.print("Sended\n");
            JOptionPane.showMessageDialog(null, "Sended");  
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_SendButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        try {

            homepage();
        } catch (SQLException ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BackButtonActionPerformed

    private void IbanTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IbanTextKeyPressed
        char c = evt.getKeyChar();
        
        if(Character.isLetter(c))
        {
            IbanText.setEditable(false);
            IBANEx.setText("Please Enter Only Number");       
        }
        else IbanText.setEditable(true);
    }//GEN-LAST:event_IbanTextKeyPressed

    private void AmountTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountTextKeyPressed
         char c = evt.getKeyChar();
        
        if(Character.isLetter(c))
        {
            AmountText.setEditable(false);
            AmountEx.setText("Please Enter Only Number");       
        }
        else AmountText.setEditable(true);
    }//GEN-LAST:event_AmountTextKeyPressed

    private void NameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTextKeyPressed
 
    }//GEN-LAST:event_NameTextKeyPressed

    private void SurnameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SurnameTextKeyPressed

    }//GEN-LAST:event_SurnameTextKeyPressed

    
    public int check() throws SQLException
    {
        try{
            String selectsql = "SELECT * FROM accounts WHERE \"First Name\" = ?";
            pst = conn.prepareStatement(selectsql);
            pst.setString(1, NameText.getText());
            ra = pst.executeQuery();
            String IBANFromDatabase = ra.getString("IBAN");
            String surnameFromDatabase = ra.getString("Last Name");
            String enteredIBAN = IbanText.getText();
            String enteredSurName = SurnameText.getText();
            ra.close();
            pst.close();
            System.out.print("asdasasfsaagas\n");
            if (IBANFromDatabase != null && surnameFromDatabase != null && IBANFromDatabase.equals(enteredIBAN)&& surnameFromDatabase.equals(enteredSurName))
                return 1;       
       }catch(SQLException ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception e)
        {
            
        }
        return 0;
    }
    
    
    public void homepage() throws SQLException
    {
        String updateQuery = "SELECT * FROM accounts WHERE ID = ?";
        pst = conn.prepareStatement(updateQuery);
        pst.setInt(1, sendingID);
        ra = pst.executeQuery();
        setVisible(false);
        Home ob = null;
        try {
            ob = new Home(ra);
        } catch (SQLException ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.print("Homepage\n");
        ob.setVisible(true);
    }
    
    public void Sendingaccount() throws SQLException
    {
        String updateQuery = "UPDATE accounts SET Balance = Balance - " + Integer.valueOf(AmountText.getText()) + " WHERE ID = ?";
        try
        {
        pst = conn.prepareStatement(updateQuery);
        pst.setInt(1,sendingID);
        pst.execute();
        ra.close();
        pst.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    
     public void Receivingaccount() throws SQLException
    {
        String updateQuery = "UPDATE accounts SET Balance = Balance + " + Integer.valueOf(AmountText.getText()) + " WHERE IBAN = ?";
        try
        {    
        pst = conn.prepareStatement(updateQuery);
        pst.setString(1, IbanText.getText());
        pst.execute();
        pst.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
     

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountEx;
    private javax.swing.JTextField AmountText;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField BalanceText;
    private javax.swing.JLabel IBANEx;
    private javax.swing.JLabel IbanLabel;
    private javax.swing.JTextField IbanText;
    private javax.swing.JLabel NameEx;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JButton SendButton;
    private javax.swing.JLabel SurnameEx;
    private javax.swing.JLabel SurnameLabel;
    private javax.swing.JTextField SurnameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
