
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author atura
 */
public class Transaction extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet ra = null;
    Statement st = null;
    int sendingID;
    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
    }
    public Transaction(ResultSet ra) throws SQLException {
        initComponents();
        this.ra = ra;
        conn = BankDBConnection.connectBankDB();
        BalanceText.setText(ra.getString("Balance"));
        sendingID = ra.getInt("ID");
        BalanceText.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        IBANEx = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        NameEx = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AmountEx = new javax.swing.JLabel();
        SendButton = new javax.swing.JButton();
        AmountText = new javax.swing.JTextField();
        IbanText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();
        BalanceText = new javax.swing.JTextField();
        IbanLabel = new javax.swing.JLabel();
        SurnameLabel = new javax.swing.JLabel();
        SurnameEx = new javax.swing.JLabel();
        SurnameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NameLabel.setText("First Name:");

        IBANEx.setForeground(new java.awt.Color(255, 51, 51));
        IBANEx.setText(" ");

        BackButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        NameEx.setForeground(new java.awt.Color(255, 51, 0));
        NameEx.setText(" ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Balance:");

        AmountEx.setForeground(new java.awt.Color(255, 51, 0));
        AmountEx.setText(" ");

        SendButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SendButton.setText("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        AmountText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AmountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AmountTextKeyPressed(evt);
            }
        });

        IbanText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IbanText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IbanTextKeyPressed(evt);
            }
        });

        NameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });
        NameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameTextKeyPressed(evt);
            }
        });

        BalanceText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BalanceText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        IbanLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IbanLabel.setText("IBAN:");

        SurnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SurnameLabel.setText("Last Name:");

        SurnameEx.setForeground(new java.awt.Color(255, 51, 0));
        SurnameEx.setText(" ");

        SurnameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SurnameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SurnameTextKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Amount:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SurnameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(NameText)
                                .addComponent(SurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IbanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BalanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IbanText, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AmountEx)
                    .addComponent(IBANEx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SurnameEx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NameEx))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BalanceText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IbanLabel)
                    .addComponent(IbanText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(IBANEx)
                        .addGap(45, 45, 45)
                        .addComponent(NameEx))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameLabel)
                            .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SurnameLabel)
                            .addComponent(SurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(AmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(SurnameEx))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(AmountEx))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Money Transfer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        setSize(new java.awt.Dimension(491, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SurnameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SurnameTextKeyPressed

    }//GEN-LAST:event_SurnameTextKeyPressed

    private void NameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameTextKeyPressed

    }//GEN-LAST:event_NameTextKeyPressed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void IbanTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IbanTextKeyPressed
        char c = evt.getKeyChar();

        if(Character.isLetter(c))
        {
            IbanText.setEditable(false);
        }
        else IbanText.setEditable(true);
    }//GEN-LAST:event_IbanTextKeyPressed

    private void AmountTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AmountTextKeyPressed
        char c = evt.getKeyChar();

        if(Character.isLetter(c))
        {
            AmountText.setEditable(false);
        }
        else AmountText.setEditable(true);
    }//GEN-LAST:event_AmountTextKeyPressed

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed

        try{
            if (ra != null)
                ra.close();
            if((Integer.parseInt(BalanceText.getText())) < (Integer.parseInt(AmountText.getText())))
            {
                System.out.print("Insufficient balance\n");
                JOptionPane.showMessageDialog(null, "Insufficient balance");
                return;
            }
            if (check() == 0)
            {
                System.out.print("The entered information does not match\n");
                JOptionPane.showMessageDialog(null, "The entered information does not match");
                return;
            }
            String transql = "insert into transactions values (?, ?, ?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(transql);
            Random a = new Random();
            pst.setInt(1, (a.nextInt(900000) + 100000));
            pst.setString(2, (Integer.toString(sendingID)));
            String time = LocalDateTime.now().toString();
            pst.setString(3, time);
            pst.setString(4, AmountText.getText());
            pst.setString(5, IbanText.getText());
            pst.setString(6, NameText.getText());
            pst.setString(7, SurnameText.getText());   
            pst.execute();
            pst.close();
            st = conn.createStatement();
            ra = st.executeQuery("SELECT * FROM accounts WHERE ID=" + (Integer.toString(sendingID)));
            pst.close();
            Sendingaccount();
            Receivingaccount();
            homepage();
            System.out.print("Sended\n");
            JOptionPane.showMessageDialog(null, "Sended");
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_SendButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        try {
               
            homepage();
        } catch (SQLException ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BackButtonActionPerformed

    
    public int check() throws SQLException
    {
        try{
            String selectsql = "SELECT * FROM accounts WHERE \"First Name\" = ?";
            pst = conn.prepareStatement(selectsql);
            pst.setString(1, NameText.getText());
            ra = pst.executeQuery();
            if (ra.next()) 
            {
            String IBANFromDatabase = ra.getString("IBAN");
            String surnameFromDatabase = ra.getString("Last Name");
            String enteredIBAN = IbanText.getText();
            String enteredSurName = SurnameText.getText();

            ra.close();

            if (IBANFromDatabase != null && surnameFromDatabase != null && IBANFromDatabase.equals(enteredIBAN) && surnameFromDatabase.equals(enteredSurName))
                return 1;
            }
        }catch(SQLException ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception e)
        {
            System.out.println("Hataaağğ");
        }
        return 0;
    }
    
    
    public void homepage() throws SQLException
    {
        String updateQuery = "SELECT * FROM accounts WHERE ID = ?";
        pst = conn.prepareStatement(updateQuery);
        pst.setInt(1, sendingID);
        ra = pst.executeQuery();
        setVisible(false);
        Home ob = null;
        try {
            ob = new Home(ra);
        } catch (SQLException ex) {
            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.print("Homepage\n");
        ob.setVisible(true);
        dispose();
    }
    
    public void Sendingaccount() throws SQLException
    {
        String updateQuery = "UPDATE accounts SET Balance = Balance - " + Integer.valueOf(AmountText.getText()) + " WHERE ID = ?";
        try
        {
        pst = conn.prepareStatement(updateQuery);
        pst.setInt(1,sendingID);
        pst.execute();
        ra.close();
        pst.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }catch(Exception e)
        {
            
        }
    }
    
     public void Receivingaccount() throws SQLException
    {
        String updateQuery = "UPDATE accounts SET Balance = Balance + " + Integer.valueOf(AmountText.getText()) + " WHERE IBAN = ?";
        try
        {    
        pst = conn.prepareStatement(updateQuery);
        pst.setString(1, IbanText.getText());
        pst.execute();
        pst.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }catch(Exception e)
        {
            
        }
    }
     

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountEx;
    private javax.swing.JTextField AmountText;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField BalanceText;
    private javax.swing.JLabel IBANEx;
    private javax.swing.JLabel IbanLabel;
    private javax.swing.JTextField IbanText;
    private javax.swing.JLabel NameEx;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JButton SendButton;
    private javax.swing.JLabel SurnameEx;
    private javax.swing.JLabel SurnameLabel;
    private javax.swing.JTextField SurnameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
